version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/src:/code
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  postgres_data:
